/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyek4;

import java.util.*;
import javax.swing.*;


/**
 *
 * @author LENOVO
 */


public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    DefaultListModel<String> model = new DefaultListModel<>();
    List<String> dataList = new ArrayList<>();
    Set<String> dataSet = new HashSet<>();
    Map<Integer, String> dataMap = new HashMap<>();
    int mapKeyCounter = 0;

    public MainFrame() {
        initComponents();
        itemList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList<>();
        btnClearAll = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtItemName = new javax.swing.JTextField();
        btnSaveList = new javax.swing.JButton();
        btnInsertList = new javax.swing.JButton();
        btnSaveSet = new javax.swing.JButton();
        btnInsertSet = new javax.swing.JButton();
        btnSaveMap = new javax.swing.JButton();
        btnInsertMap = new javax.swing.JButton();
        lblListCount = new javax.swing.JLabel();
        lblSetCount = new javax.swing.JLabel();
        lblMapCount = new javax.swing.JLabel();
        jLabelItemName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(itemList);

        btnClearAll.setText("Clear all");
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });

        btnAdd.setText("add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSaveList.setText("save to List");
        btnSaveList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveListActionPerformed(evt);
            }
        });

        btnInsertList.setText("insert data List");
        btnInsertList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertListActionPerformed(evt);
            }
        });

        btnSaveSet.setText("save to Set");
        btnSaveSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSetActionPerformed(evt);
            }
        });

        btnInsertSet.setText("insert data Set");
        btnInsertSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertSetActionPerformed(evt);
            }
        });

        btnSaveMap.setText("save to Map");
        btnSaveMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMapActionPerformed(evt);
            }
        });

        btnInsertMap.setText("insert data Map");
        btnInsertMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertMapActionPerformed(evt);
            }
        });

        lblListCount.setText("Data tersimpan = 0");

        lblSetCount.setText("Data tersimpan = 0");

        lblMapCount.setText("Data tersimpan = 0");

        jLabelItemName.setText("Item Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertMap)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSaveList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsertList, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(btnInsertSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSetCount)
                                    .addComponent(lblMapCount)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblListCount))))
                    .addComponent(jLabelItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveList)
                            .addComponent(lblListCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertList)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveSet)
                            .addComponent(lblSetCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertSet)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveMap)
                            .addComponent(lblMapCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertMap)
                        .addGap(52, 52, 52)
                        .addComponent(jLabelItemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearAll)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertSetActionPerformed
        String item = txtItemName.getText();
        if (!item.isEmpty()) {
            dataSet.add(item);
            lblSetCount.setText("Data tersimpan = " + dataSet.size());
        }
    }//GEN-LAST:event_btnInsertSetActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        model.clear();
    }//GEN-LAST:event_btnClearAllActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String item = txtItemName.getText();
        if (!item.isEmpty()) {
            model.addElement(item);
            txtItemName.setText("");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int index = itemList.getSelectedIndex();
        if (index >= 0) {
            model.remove(index);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveListActionPerformed
        dataList.clear();
        for (int i = 0; i < model.getSize(); i++) {
            dataList.add(model.getElementAt(i));
        }
        lblListCount.setText("Data tersimpan = " + dataList.size());
    }//GEN-LAST:event_btnSaveListActionPerformed

    private void btnInsertListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertListActionPerformed
        String item = txtItemName.getText();
        if (!item.isEmpty()) {
            dataList.add(item);
            lblListCount.setText("Data tersimpan = " + dataList.size());
        }
    }//GEN-LAST:event_btnInsertListActionPerformed

    private void btnSaveSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSetActionPerformed
        dataSet.clear();
        for (int i = 0; i < model.getSize(); i++) {
            dataSet.add(model.getElementAt(i));
        }
        lblSetCount.setText("Data tersimpan = " + dataSet.size());
    }//GEN-LAST:event_btnSaveSetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int index = itemList.getSelectedIndex();
        String newItem = txtItemName.getText();
        if (index >= 0 && !newItem.isEmpty()) {
            model.set(index, newItem);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMapActionPerformed
        dataMap.clear();
        mapKeyCounter = 0;
        for (int i = 0; i < model.getSize(); i++) {
            dataMap.put(mapKeyCounter++, model.getElementAt(i));
        }
        lblMapCount.setText("Data tersimpan = " + dataMap.size());
    }//GEN-LAST:event_btnSaveMapActionPerformed

    private void btnInsertMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertMapActionPerformed
        String item = txtItemName.getText();
        if (!item.isEmpty()) {
            dataMap.put(mapKeyCounter++, item);
            lblMapCount.setText("Data tersimpan = " + dataMap.size());
        }
    }//GEN-LAST:event_btnInsertMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsertList;
    private javax.swing.JButton btnInsertMap;
    private javax.swing.JButton btnInsertSet;
    private javax.swing.JButton btnSaveList;
    private javax.swing.JButton btnSaveMap;
    private javax.swing.JButton btnSaveSet;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JList<String> itemList;
    private javax.swing.JLabel jLabelItemName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListCount;
    private javax.swing.JLabel lblMapCount;
    private javax.swing.JLabel lblSetCount;
    private javax.swing.JTextField txtItemName;
    // End of variables declaration//GEN-END:variables
}
